### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by vikramsesh** [arve0/fijibin#4]
I am unable to run this on a Raspberry Pi. 
Everytime I run fijibin.macro.run(macro) I get this error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/miniconda3/lib/python3.4/site-packages/fijibin/macro.py", line 77, in run
    stderr=subprocess.PIPE, env=env)
  File "/home/pi/miniconda3/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/home/pi/miniconda3/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error 

I am trying to use fijibin to an existing python script with GUI to do some image analysis.
Would appreciate the help.

**Comment by arve0** [comment]
Hi, and thanks for reporting. Do you have steps to reproduce?

**Comment by vikramsesh** [comment]
Installed ImageJ according to this site: https://imagej.net/Raspberry_Pi
Installed fijibin based on this: https://pypi.org/project/fijibin/

**Python Script:**
import fijibin
import fijibin.macro

new_macro = """ open("/home/pi/Desktop/My files/cameraui.png");
run("Measure");
saveAs("Results", "/home/pi/Desktop/My files/Results.csv");
close();
"""
fijibin.macro.run(new_macro)

**Error**
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    fijibin.macro.run(new_macro)
  File "/home/pi/fijibin/fijibin/macro.py", line 77, in run
    stderr=subprocess.PIPE, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.bin/Fiji-20141125.app/ImageJ-linux32'

**Comment by arve0** [comment]
Probably because raspberry is an ARM processor. You could try setting `fijibin.BIN` to the executable that you have installed.
